### ISSUE TITLE
update puppeteer to latest version (13+)

### ISSUE THREAD

**Issue by GlenDC** [unblocked-web/double-agent#61]
Currently the puppeteer version in this repo's runner implementation for puppeteer is at a very old version (v2), while we're already 11 major versions further (v13). As can be seen at <https://www.npmjs.com/package/puppeteer>.

I tried this locally on my own repo (which makes use of double-agent) and that seems to work fine without any changes. Only thing that did change is that the assignments result in generating a storm of pop-ups for saving a downloaded file, so that's the only thing that I notice that probably does require addressing somehow.

**Comment by blakebyrnes** [comment]
Assuming we are still using Axios to get all the assignments and results, I wonder how/where that's turning into something puppeteer sees.

**Comment by blakebyrnes** [comment]
Fixed in latest push
